name: Daily Kaggle Notebook Update

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  update-notebook:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Update notebook timestamp
      run: |
        NOW=$(date)
        sed -i "s|Auto-updated:.*|Auto-updated: $NOW|g" daily_activity_notebook.ipynb

    - name: Commit and push
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git commit -am "Daily update: $NOW" || echo "No changes"
        git push
